name: amritdhara
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ADDED FOR LOCALIZATION (Multilingual Support)
  flutter_localizations:
    sdk: flutter

  csv: ^5.0.0
  google_maps_flutter: ^2.5.0
  permission_handler: ^11.0.1
  geolocator: ^10.1.0
  http: ^1.2.0
  network_info_plus: ^4.0.2
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # ADDED FOR LOCALIZATION (Enables auto code generation)
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - lib/rainwater_backend/gwl.csv
    - lib/rainwater_backend/pincodes_of_india.csv
    - lib/rainwater_backend/predictions_2025.csv
    - lib/rainwater_backend/soil_texture.csv